stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: php-example:${CICD_EXECUTION_SEQUENCE}
    env:
      MIRROR: "https://registry.docker-cn.com"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
