stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: lawr/demo:${CICD_EXECUTION_SEQUENCE}
      registry: index.docker.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
